seed_everything: 36
trainer:
  enable_checkpointing: true
  accelerator: gpu
  devices: 1
  deterministic: false

  max_epochs: 300
  check_val_every_n_epoch: 4
  num_sanity_val_steps: 1
  log_every_n_steps: 250

callbacks:
  - class_path: pytorch_lightning.callbacks.LearningRateMonitor
    init_args:
      logging_interval: epoch
  - class_path: pytorch_lightning.callbacks.ModelCheckpoint
    init_args:
      save_top_k: 1
      monitor: val_ExpRate
      mode: max
      filename: '{epoch}-{step}-{val_ExpRate:.4f}'

wandb:
 name: d_model 128 seed 36
 project: "HMER"
 log_model: "all"

model:
  d_model: 128
  # encoder
  growth_rate: 24
  num_layers: 16
  # decoder
  nhead: 8
  num_decoder_layers: 6
  dim_feedforward: 512
  dropout: 0.3
  attn_dropout: 0.3
  dc: 32
  cross_coverage: true
  self_coverage: true
  num_experts: 4
  qk_norm: false
  # beam search
  beam_size: 10
  max_len: 200
  alpha: 1.0
  early_stopping: false
  temperature: 1.0
  # training
  learning_rate: 0.08
  patience: 16
  group_decay: false
  l_aux_weight: 0.01
  use_moe: false
  perturb_mode: "none" # none radom  structure_random
  perturb_prob: 0.0

data:
  zipfile_path: data.zip
  test_year: "2014"
  train_batch_size: 2
  eval_batch_size: 2
  num_workers: 12
  scale_aug: true
